### ISSUE TITLE
Messenger Platform 1.4 released

### ISSUE THREAD

**Issue by ansarizafar** [botmasterai/botmaster-messenger#1]
Messenger Platform 1.4 has updated/introduced new APIs for bot builders. Please check this link [https://messengerblog.com/platform-updates/messenger-platform-1-4-brings-even-more-tools-to-build-great-experiences/](https://messengerblog.com/platform-updates/messenger-platform-1-4-brings-even-more-tools-to-build-great-experiences/) 

Here is the change log [https://developers.facebook.com/docs/messenger-platform/changelog?__mref=message_bubble](https://developers.facebook.com/docs/messenger-platform/changelog?__mref=message_bubble)

**Comment by jdwuarin** [comment]
Hi Ansari, This latest version of `botmaster-messenger` should come with all the requested additions. They are all referenced in this projects API section of the Readme: https://github.com/botmasterai/botmaster-messenger#api
