### ISSUE TITLE
Update crypto and babel-preset-es2015

### ISSUE THREAD

**Issue by marcelothomaz** [botmasterai/botmaster-messenger#10]
Hi

Crypto is now built-in Node and babel-preset-es2015 became babel-preset-env
A migration should be reasonable

Regards

**Comment by jdwuarin** [comment]
Yeah - I do agree. If you want to send us a pull request, I'll be happy to review it and potentially merge it. That way you'd become a contributor!

**Comment by jdwuarin** [comment]
Fixed by: 477650a77d18a5bf104562bdb66b734f57bd97e3
