### ISSUE TITLE
Botmaster messenger page won't reply

### ISSUE THREAD

**Issue by string-args** [botmasterai/botmaster-messenger#12]
Hi I've built a facebook test page and integrated it with the botmaster-messenger. And I have already setup all the required settings in facebook and botmaster itself. When using the admin account of the page, the messenger bot works well. But when i tried to use other accounts, the messenger isn't replying. Is there any specific setups needed for it to work with other users?

**Comment by bobber205** [comment]
Have you been approved for messenger permissions for your app?
If you haven't then it only will allow you to respond to admins.

**Comment by jdwuarin** [comment]
This is probably an issue regarding your app not being approved. Closing this unless there is a real issue
