### ISSUE TITLE
Messenger platform 2.0

### ISSUE THREAD

**Issue by ansarizafar** [botmasterai/botmaster-messenger#3]
Messenger platform 2.0 has been released. Is there any plan to implement V 2.0 new futures?

**Comment by younes0x53** [comment]
Hi, botmaster-messenger is already had the v2 features.

**Comment by marcelothomaz** [comment]
Hi, should we close this?

**Comment by jwickens** [comment]
Hi thanks for the heads up, but yes we can close this.
